# Generated by Django 2.2.7 on 2020-04-11 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('special_status', 'Cam read all books')]},
        ),
    ]
